name: Publish GHCR

on:
  push:
    branches:
      - main  # or the branch you want to trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Saeedeh-tech
          password: ${{ secrets.GHCR_PAT}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./docker  
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/saeedeh-tech/ghcr-test-image:latest
